Prefecture.create([{ prefecture: "Hokkaido" }, { prefecture: "Aomori" }, { prefecture: "Iwate" },
                    { prefecture: "Miyagi" }, { prefecture: "Akita" }, { prefecture: "Yamagata" },
                    { prefecture: "Fukushima" },{ prefecture: "Ibaraki" }, { prefecture: "Tochigi" }, 
                    { prefecture: "Gunma" },{ prefecture: "Saitama" }, { prefecture: "Chiba" }, { prefecture: "Tokyo" },
                    { prefecture: "Kanagawa" },{ prefecture: "Niigata" }, { prefecture: "Toyama" }, { prefecture: "Ishikawa" },
                    { prefecture: "Fukui" }, { prefecture: "Yamanashi" }, { prefecture: "Nagano" },
                    { prefecture: "Gifu" },{ prefecture: "Shizuoka" }, { prefecture: "Aichi" }, 
                    { prefecture: "Mie" },{ prefecture: "Shiga" }, { prefecture: "Kyoto" }, { prefecture: "Osaka" },
                    { prefecture: "Hyogo" },{ prefecture: "Nara" }, { prefecture: "Wakayama" }, { prefecture: "Tottori" },
                    { prefecture: "Shimane" }, { prefecture: "Okayama" },
                    { prefecture: "Hiroshima" },{ prefecture: "Yamaguchi" }, { prefecture: "Tokushima" }, 
                    { prefecture: "Kagawa" },{ prefecture: "Ehime" }, { prefecture: "Kochi" }, { prefecture: "Fukuoka" },
                    { prefecture: "Saga" },{ prefecture: "Nagasaki" }, { prefecture: "Kumamoto" }, 
                    { prefecture: "Oita" },{ prefecture: "Miyazaki" }, { prefecture: "Kagoshima" }, { prefecture: "Okinawa" },])
